version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dev@1Ter
      - POSTGRES_DB=develop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
